
// TODO: Switch with string impl
export enum EventType {
    fluid_intake_observation = "fluid_intake_observation",
    task_completed = "task_completed",
    physical_health_observation = "physical_health_observation",
    visit_completed = "visit_completed",
    check_out = "check_out",
    mood_observation = "mood_observation",
    regular_medication_taken = "regular_medication_taken",
    alert_raised = "alert_raised",
    no_medication_observation_received = "no_medication_observation_received",
    incontinence_pad_observation = "incontinence_pad_observation",
    check_in = "check_in",
    general_observation = "general_observation",
    regular_medication_not_taken = "regular_medication_not_taken",
    food_intake_observation = "food_intake_observation",
    task_completion_reverted = "task_completion_reverted",
    mental_health_observation = "mental_health_observation",
    medication_schedule_updated = "medication_schedule_updated",
    visit_cancelled = "visit_cancelled",
    regular_medication_maybe_taken ="regular_medication_maybe_taken",
    medication_schedule_created = "medication_schedule_created",
    alert_qualified = "alert_qualified",
    task_schedule_created = "task_schedule_created",
    concern_raised = "concern_raised",
    regular_medication_partially_taken= "regular_medication_partially_taken",
    catheter_observation = "catheter_observation",
    toilet_visit_recorded = "toilet_visit_recorded"
}